package com.ordermanager.exception;

public enum BinanceErrorType {
    RATE_LIMIT,
    TIMESTAMP_ERROR,
    AUTH_ERROR,
    INVALID_SIGNATURE,
    INVALID_SYMBOL,
    INSUFFICIENT_BALANCE,
    DUPLICATE_ORDER,
    FILTER_VIOLATION,
    ORDER_NOT_FOUND,
    CANCEL_REJECTED,
    ORDER_REJECTED,
    MARKET_CLOSED,
    ACCOUNT_TRADING_DISABLED,
    NETWORK_ERROR,
    UNKNOWN
}
